files:
  - source: /docs/**/*
    ignore:
      - install-sui.mdx
      - gas-in-sui.mdx
      - sui-json-format.mdx
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    languages_mapping:
      two_letters_code:
        zh-CN: zh-CN
        zh-TW: zh-TW
